import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary-background">
        <div className="font-primary w-full flex justify-center p-14 text-2xl font-semibold text-primary-main">
          SUDOKU
        </div>
        {children}
      </body>
    </html>
  );
}
