export const CELLS_PER_LINE = 9;
export const DEFAULT_GAME_CELL_IN_PX = 50;
export const DEFAULT_SQUARE_SIZE_IN_PX = 150;
export const DEFAULT_BOARD_SIZE =
  CELLS_PER_LINE * DEFAULT_GAME_CELL_IN_PX +
  (DEFAULT_SQUARE_SIZE_IN_PX / DEFAULT_GAME_CELL_IN_PX) * 2;
